### ISSUE TITLE
colour/darkMode derived from backgroundColor and focus/blur styles

### ISSUE THREAD

**Issue by timfish** [sidneys/electron-titlebar-windows#10]
We've been using some code [similar to this](https://stackoverflow.com/a/3943023/106623) to automatically choose a foreground text colour for any background colour. This could be used in electron-titlebar-windows if the user doesn't supply `color` or `darkMode`, we could calculate these for them.

We're also using the following CSS plus BrwoserWindow `focus` and `blur` events to add and remove `window-focus` from the body to give more native blur/focus styling of the titlebar:
```css
    body:not(.window-focus) .titlebar {
      filter: opacity(.6) grayscale(50%);
    }
```

I did notice that electron-titlebar-windows doesn't currently reference any electron code, would you like to keep it this way?
